name: Deploy

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/cache@v2.1.5
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Check install Hugo
        run: hugo version

      - name: Compile files
        run: hugo -D

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: endsWith(github.ref, '/master') || endsWith(github.ref, '/test')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: hasankeklik.com
          commit_message: ${{ github.event.head_commit.message }}
          user_name: Hasan Keklik
          user_email: keklikhasan@gmail.com